language: rust
rust:
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo test --all --release
  - cd ethbloom && cargo build --no-default-features
  - cd ethereum-types && cargo build --no-default-features
env:
  - RUST_LOG=quickcheck
