language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo test -p ethereum-types --no-default-futures
  - cargo test -p tests
env:
  - RUST_LOG=quickcheck
