[package]
description = "Large fixed-size integers arithmetics"
homepage = "http://parity.io"
repository = "https://github.com/ethcore/bigint"
license = "GPL-3.0"
name = "bigint"
version = "0.1.2"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"

[build-dependencies]
rustc_version = "0.1"

[dependencies]
rustc-serialize = "0.3"
heapsize = "0.3"
rand = "0.3.12"

[features]
x64asm_arithmetic=[]
rust_arithmetic=[]
