[package]
name = "ethereum-types"
version = "0.3.3"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
homepage = "https://github.com/paritytech/primitives"
description = "Ethereum types"
build = "build.rs"

[build-dependencies]
rustc_version = "0.2"

[dependencies]
crunchy = "0.1.5"
ethbloom = { path = "../ethbloom", version = "0.5.0", default-features = false }
ethereum-types-serialize = { version = "0.2.1", path = "../serialize", optional = true }
# TODO: remove `branch` when https://github.com/paritytech/parity-common/pull/12 lands
fixed-hash = { git = "https://github.com/paritytech/parity-common", branch = "add-fixed-hash", default_features = false }
serde = { version = "1.0", optional = true }
# TODO: remove `branch` when https://github.com/paritytech/parity-common/pull/12 lands
uint = { git = "https://github.com/paritytech/parity-common", branch = "add-fixed-hash", default_features = false }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["std", "heapsizeof", "serialize"]
std = ["uint/std", "fixed-hash/std", "ethbloom/std"]
heapsizeof = ["uint/heapsizeof", "fixed-hash/heapsizeof", "ethbloom/heapsizeof"]
serialize = ["std", "ethereum-types-serialize", "serde", "ethbloom/serialize"]
use_asm = ["uint/use_asm"]
impl_quickcheck_arbitrary = ["uint/impl_quickcheck_arbitrary", "fixed-hash/impl_quickcheck_arbitrary"]
