[package]
name = "ethereum-types"
version = "0.5.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
homepage = "https://github.com/paritytech/primitives"
description = "Ethereum types"

[dependencies]
crunchy = { version = "0.2", default-features = false }
ethbloom = { path = "../ethbloom", version = "0.6", default-features = false }
fixed-hash = { version = "0.3", default-features = false, features = ["byteorder", "rustc-hex"] }
uint = { version = "0.5", default-features = false }
primitive-types = { version = "0.1", features = ["rlp", "byteorder", "rustc-hex"], default-features = false }
impl-serde = { version = "0.1", default-features = false, optional = true }
impl-rlp = { version = "0.1", default-features = false }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["std", "heapsize", "serialize"]
std = ["uint/std", "fixed-hash/std", "ethbloom/std", "crunchy/std", "primitive-types/std"]
heapsize = ["uint/heapsize", "primitive-types/heapsize", "fixed-hash/heapsize", "ethbloom/heapsize"]
serialize = ["std", "impl-serde", "primitive-types/serde", "ethbloom/serialize"]
