[package]
description = "Large fixed-size integers arithmetics"
homepage = "http://parity.io"
repository = "https://github.com/paritytech/parity-common"
license = "MIT/Apache-2.0"
name = "uint"
version = "0.5.0-beta.0"
authors = ["Parity Technologies <admin@parity.io>"]
readme = "README.md"

[dependencies]
byteorder = { version = "1", default-features = false }
heapsize = { version = "0.4.2", optional = true }
rustc-hex = { version = "2.0", default-features = false }
quickcheck = { version = "0.6", optional = true }
crunchy = "0.2"

[features]
default = ["std", "common"]
std = ["byteorder/std", "rustc-hex/std"]
common = []

[[example]]
name = "modular"

[[test]]
name = "uint_tests"
