[package]
name = "trie-standardmap"
description = "Standard test map for profiling tries"
version = "0.1.1"
authors = ["debris <marek.kotewicz@gmail.com>", "Parity Technologies <admin@parity.io>"]
repository = "https://github.com/paritytech/parity-common"
license = "GPL-3.0"

[dependencies]
ethereum-types = "0.4"
keccak-hash = { path = "../keccak-hash" }
parity-bytes = { path = "../parity-bytes" }
rlp = {  path = "../rlp" }
