[package]
name = "ethbloom"
version = "0.6.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Ethereum bloom filter"
license = "MIT"
documentation = "https://docs.rs/ethbloom"
homepage = "https://github.com/paritytech/primitives"
repository = "https://github.com/paritytech/primitives"

[dependencies]
tiny-keccak = "1.4"
crunchy = { version = "0.2.1", default-features = false, features = ["limit_256"] }
rustc-hex = { version = "2.0" }
fixed-hash = { version = "0.3.0", default_features = false }
ethereum-types-serialize = { version = "0.2.1", path = "../serialize", optional = true }
serde = { version = "1.0", optional = true }

[dev-dependencies]
rand = { version = "0.4" }
hex-literal = "0.1.1"

[features]
default = ["std", "heapsize", "serialize", "fixed-hash/libc", "fixed-hash/rustc-hex"]
std = ["fixed-hash/std", "crunchy/std"]
heapsize = ["fixed-hash/heapsize"]
serialize = ["std", "ethereum-types-serialize", "serde"]
