[package]
name = "fixed-hash"
version = "0.2.4"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
homepage = "https://github.com/paritytech/parity-common"
repository = "https://github.com/paritytech/parity-common"
description = "Macros to define custom fixed-size hash types"

[dependencies]
heapsize = { version = "0.4", optional = true }
rand = { version = "0.4", optional = true, default-features = false }
rustc-hex = { version = "2.0", optional = true, default-features = false }
quickcheck = { version = "0.7", optional = true }
static_assertions = "0.2"
byteorder = { version = "1.2.7", default-features = false }

[target.'cfg(not(target_os = "unknown"))'.dependencies]
libc = { version = "0.2", optional = true, default-features = false }

[features]
default = ["std", "libc", "rand-support", "rustc-hex-support"]
std = ["rustc-hex/std", "rand/std"]

rustc-hex-support = ["rustc-hex"]
rand-support = ["rand"]
heapsize-support = ["heapsize"]
quickcheck-support = ["quickcheck"]
